### ISSUE TITLE
Phone Number username are hashed in backend but not on client.

### ISSUE THREAD

**Issue by kibagateaux** [aws-samples/aws-mobile-react-native-starter#25]
I've been trying to hunt this bug for a while but I can't figure out for the life of me so I am hoping you guys can give some advice. I have my Cognito User Pool setup so that my users signup with their phone number as their username.

Login and everything works fine but in the library (or somewhere, I have no idea) the phone number gets hashed during login but it is not returned as a hash so there is a discrepancy between what is saved in local storage after login and the actual username in Cognito.

So far this isn't a serious problem but I have just started building my app and using AWS so I want to get it fixed before I start using your other services. Is there a different advised method for identifying users to persist data? My first time using any AWS so I don't have any domain knowledge when it comes to your services/frameworks.

To view you can add logging to `getCognitoCredentials` function in `client/lib/Categories/Auth/Auth` and compare this log statement to local storage after login. Your local storage will have unhashed phone number but in the function you can see the hashed username. Even though it is visible in the logs it is actually added after the fact because I have tried intercepting it.

For clarity:

>User signs up
>Auto confirm signup with Lambda trigger
> User signs in
> Sign in success!
> Everything AWS works great
> Access username to save in Dynamo
> Data saves under raw phone number
> No errors just a bug, app works just fine on Android and iOS

**Comment by mlabieniec** [comment]
we can pass this on to the service team as a feature request
