### ISSUE TITLE
hello I would like to collaborate with your project by serving as a translator to Spanish which is my native language. could translate any text provided it is a thousand words or more

### ISSUE THREAD

**Issue by LuigiBaute** [aws-samples/aws-mobile-react-native-starter#62]

**Comment by powerful23** [comment]
@LuigiBaute sure you can submit a pr to us.

**Comment by LuigiBaute** [comment]
Hi @powerful23 Look at what git hub told me when I tried making a pull request
`Review required
At least one approved review is required by reviewers with write access. 
Merging is blocked
Merging can be performed automatically with one approved review.`
the file its done check it out and let me know any suggestions I'll gladly change it as many times as necessary. :)

**Comment by UnleashedMind** [comment]
Thank you. We got the PR, and it has been assigned to one of our Spanish speaking colleagues to review.

**Comment by LuigiBaute** [comment]
Hi, @UnleashedMind your colleague hasn't checked it yet?

**Comment by mlabieniec** [comment]
merged
