### ISSUE TITLE
Gradle version error on Android build

### ISSUE THREAD

**Issue by Rick49** [aws-samples/aws-mobile-react-native-starter#66]
A am able to run the example program in the IOS simulator, but when I try to run on android (npm run android), it fails to build.  
ANDROID_HOME is properly assigned
Android Studio is installed, with SDKs 23 and 27
Error message:
`FAILURE: Build failed with an exception.

* Where:
Build file '/Users/rick/Documents/JuvaCare/jcg/node_modules/amazon-cognito-identity-js/android/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':amazon-cognito-identity-js'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/LibraryPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

the build.gradle file looks like this:

`buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.facebook.react:react-native:+'
}
`

**Comment by elorzafe** [comment]
Hi @Rick49 

I just ran the steps for android (Before I start an android emulator instance) and I got working. Can you try removing node modules and installing again.

I was using this emulator

Name: Pixel_XL_API_23

CPU/ABI: Google APIs Intel Atom (x86_64)

Target: google_apis [Google APIs] (API level 23)

Skin: pixel_xl

SD Card: 100M

hw.dPad: no

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_xl

vm.heapSize: 256

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.initialOrientation: Portrait

image.androidVersion.api: 23

hw.audioInput: yes

image.sysdir.1: system-images/android-23/google_apis/x86_64/

tag.id: google_apis

showDeviceFrame: yes

hw.camera.back: emulated

hw.mainKeys: no

AvdId: Pixel_XL_API_23

hw.camera.front: emulated

hw.lcd.density: 560

avd.ini.displayname: Pixel XL API 23

hw.gpu.mode: auto

hw.device.hash2: MD5:9b564b60b1aebee32c73ded9daa1e620

hw.ramSize: 1536

hw.trackBall: no

PlayStore.enabled: false

hw.battery: yes

hw.cpu.ncore: 2

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

hw.keyboard: yes

hw.sensors.proximity: yes

disk.dataPartition.size: 800M

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes


Please let me know if this problem continues

**Comment by mlabieniec** [comment]
closing for now, please let us know if you are still having the issue.
