### ISSUE TITLE
login deadlock  - sms problem

### ISSUE THREAD

**Issue by smustaoglu** [aws-samples/aws-mobile-react-native-starter#69]
I cant send sms with free-tier. İs it problem of limit? support dont want to increase the limit. it is free-tier.. :(
how to disable sms verification..... otherwise we cannot test this project...
i am in deadlock.

how to disable sms verification.
or sms setting for free tier to work....
{
"notification": {
"messageId": "b981962a-e36d-5dec-ae41-c52832953787",
"timestamp": "2018-03-10 00:58:32.562"
},
"delivery": {
"destination": "+905302345671",
"smsType": "Transactional",
"providerResponse": "Internal error",
"dwellTimeMs": 64
},
"status": "FAILURE"
}

**Comment by nidsharm** [comment]
Hi @smustaoglu,

If SMS verification isn't working for you, you can go to your User Pool on Cognito's console, click on 'MFA and verifications' tab under General Settings. Under the 'Do you want to require verification of emails or phone numbers?' section, you can untick the Phone Number option and save changes. 
Then retry Signing up and Signing in with the project. 

Do let us know if you face any issues with this.
Thanks.

**Comment by mlabieniec** [comment]
closing for now, let us know if you are still having any issues here.
