### ISSUE TITLE
showMFAPrompt not align with user pool settings

### ISSUE THREAD

**Issue by smustaoglu** [aws-samples/aws-mobile-react-native-starter#71]
In Login.js always show verification code popup.
it doesnt read from user setting from pool.

**Comment by nidsharm** [comment]
Hi @smustaoglu,

The Authentication module in this project requires MFA to be enabled on your user pools. It doesn't read the user pool settings to see of MFA is enabled or not.

**Comment by nidsharm** [comment]
HI @smustaoglu ,

Please feel free to re-open the issue if you have any questions. I'm closing it for the time being.

Thanks.
