### ISSUE TITLE
Download aws-exports.js is unclear

### ISSUE THREAD

**Issue by hollyewhite** [aws-samples/aws-mobile-react-native-starter#73]
In "Use features in your app." the instructions say to "Download the `aws-exports.js` file from your AWS MobileHub project as outlined earlier in the Getting started section. Place it in the root of your new CRNA directory."

In the "Getting Started" section there is no reference to that file, nor is it in the folder I created. Could you please clarify? 

Getting Started Section: https://screencast.com/t/5CvmnvVR
Files Downloaded Previously: https://screencast.com/t/Xhl1fpV0h

**Comment by mlabieniec** [comment]
@hollyewhite the aws-exports.js is pulled down for you via the awsmobile-cli. See the commands in the readme. You can use the `awsmobile start` command to pull / bootstrap everything. If you actually clone this with `git` then you'd need to run an `awsmobile init` within your project to retrieve the aws exports. However the recommended approach for the starter kits is to use the `awsmobile start my-project react-native` which will do everything for you (including cloning this repo).
